name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

permissions:
  contents: read

jobs:
  quality:
    name: Quality checks

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up PHP
        uses: hosmelq/.github/.github/actions/php-setup@5e5ccc13198e5168b27d183874b0ec86d0029071
        with:
          php-tools: cs2pr
          php-version: '8.4'
        env:
          fail-fast: true

      - name: Install composer dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Check composer
        run: composer normalize --dry-run

      - name: Check code quality
        run: vendor/bin/rector --ansi --dry-run

      - name: Check code style
        run: vendor/bin/pint --test

      - name: Check static code
        run: composer phpstan

      - name: Check unused composer dependencies
        run: vendor/bin/composer-dependency-analyser

  tests:
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.stability }}

    runs-on: ubuntu-latest

    services:
      mysql:
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel_auditlogs_testing
        image: mysql:8.4@sha256:0744ee5ef89ce6ccfa13de3e579fe6b9e27f93dd70da9c06d2c908b1b193fb8d
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-retries=5
          --health-timeout=5s
        ports:
          - 3306:3306

    strategy:
      fail-fast: false
      matrix:
        php: ['8.4', '8.5']
        laravel: ['12.*', '13.*']
        stability: [prefer-stable]
        include:
          - laravel: 12.*
            testbench: 10.*
          - laravel: 13.*
            testbench: 11.*

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up PHP
        uses: hosmelq/.github/.github/actions/php-setup@5e5ccc13198e5168b27d183874b0ec86d0029071
        with:
          php-tools: cs2pr
          php-version: ${{ matrix.php }}
        env:
          fail-fast: true

      - name: Install composer dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Installed dependencies
        run: composer show -D

      - name: Set up problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install composer matrix dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Run tests
        run: composer test
